### ISSUE TITLE
Domain not matched (sends default, self signed certificate)

### ISSUE THREAD

**Issue by erichulburd** [ixc/letsencrypt-docker#7]
I have an A name record pointing to my docker cloud stack IP address (see below) from api.coolclimatenetwork.net.

It seems like my letsenscrypt container doesn't match or never sees this request, since it sends back the default, self-signed SSL certificate (which browsers reject of course).

Is there something else I need to do here?

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for api.coolclimatenetwork.net
Using the webroot path /opt/www for all unmatched domains.
Waiting for verification...
66.133.109.36 - - [06/Nov/2017:02:58:09 +0000] "GET /.well-known/acme-challenge/5nfg6FYiW38MGKOTp9iIQxzEK9I7cG5gXdGnC_iN4A4 HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/api.coolclimatenetwork.net/fullchain.pem.
   Your cert will expire on 2018-02-04. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you lose your account credentials, you can recover through
   e-mails sent to opportunities@arbolista.mx.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

199.116.72.70 - - [06/Nov/2017:03:00:24 +0000] "GET / HTTP/1.1" 302 161 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
199.116.72.70 - - [06/Nov/2017:03:01:30 +0000] "GET / HTTP/1.1" 302 161 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```

Docker cloud stack: 

```
haproxy:
  environment:
    - |
      DEFAULT_SSL_CERT=...
  image: 'dockercloud/haproxy:1.6.3'
  links:
    - user-api
  ports:
    - '443:443'
  restart: on-failure
  roles:
    - global
  tags:
    - nodecluster-name=mycluster
  volumes_from:
    - letsencrypt
letsencrypt:
  environment:
    - 'DOMAINS=api.coolclimatenetwork.net'
    - EMAIL=my@email.com
    - 'HAPROXY_IMAGE=dockercloud/haproxy:1.6.3'
  image: 'interaction/letsencrypt:master'
  ports:
    - '80:80'
  restart: on-failure
  roles:
    - global
  tags:
    - nodecluster-name=mycluster
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
postgres:
  environment:
    - POSTGRES_DB=user
    - 'POSTGRES_PASSWORD=yada'
  expose:
    - '5432'
  image: 'postgres:9.4.5'
  tags:
    - nodecluster-name=mycluster
user-api:
  deployment_strategy: high_availability
  image: 'myimage:latest'
  links:
    - postgres
  ports:
    - '8082'
  restart: on-failure
  tags:
    - nodecluster-name=mycluster
```

**Comment by erichulburd** [comment]
The issue was that I pasted the key and erased the `DEFAULT_SSL_CERT=`.

This worked, although it's sending the default ssl certificate currently, which Chrome does not like. Looking into the reason why.

```
haproxy:
  environment:
    - |
      DEFAULT_SSL_CERT=...
  image: 'dockercloud/haproxy:1.6.3'
  links:
    - user-api
  ports:
    - '443:443'
  restart: on-failure
  roles:
    - global
  tags:
    - nodecluster-name=mycluster
  volumes_from:
    - letsencrypt
letsencrypt:
  environment:
    - 'DOMAINS=api.example.com,haproxy.mystack.svc.dockerapp.io'
    - EMAIL=my@email.com
    - 'HAPROXY_IMAGE=dockercloud/haproxy:1.6.3'
  image: 'interaction/letsencrypt:master'
  ports:
    - '80:80'
  restart: on-failure
  roles:
    - global
  tags:
    - nodecluster-name=mycluster
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
postgres:
  environment:
    - POSTGRES_DB=user
    - 'POSTGRES_PASSWORD=yada'
  expose:
    - '5432'
  image: 'postgres:9.4.5'
  tags:
    - nodecluster-name=mycluster
user-api:
  deployment_strategy: high_availability
  image: 'myimage:latest'
  links:
    - postgres
  ports:
    - '8082'
  restart: on-failure
  tags:
    - nodecluster-name=mycluster
```
